# -*- coding: utf-8 -*-
"""Runnables-LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-fD68sz6VbbXONnF2sEhObrSY1BIElh
"""

import random


class NakliLLM:

  def __init__(self):
    print("LLM Created")

  def predict(self, prompt):
    response_list = [
        'Delhi is the Captial of India.',
        'IPL is a cricket legaue.',
        'AI stands for Artifical Intelligence'
    ]

    return {'response': random.choice(response_list)}

llm = NakliLLM()

llm.predict('Prompt')

class NakilPromptTemplate:

  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def format(self, input_dict):
    return self.template.format(**input_dict)

template = NakilPromptTemplate(
    template = 'Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

template.format({'topic':'India'})

template.format({'length':'short', 'topic':'basketball'})

llm1 = NakliLLM()

prompt = template.format({'length':'medium', 'topic':'basketball'})

llm.predict(prompt)

class NakliLLMChain:

  def __init__(self, llm, prompt):
    self.llm = llm
    self.prompt = prompt

  def run(self, input_dict):
    final_prompt = self.prompt.format(input_dict)
    result = self.llm.predict(final_prompt)

    return result['response']

template = NakilPromptTemplate(
    template = 'Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

llm = NakliLLM()

chain = NakliLLMChain(llm, template)

chain.run({'length':'short', 'topic':'india'})

